export const emp = [
  {
    id: "1",
    image: "images",
    Name: "hukum",
    Email: "hcgupta@cstech.in",
    phone: "954010044",
    Designation: "Hr",
    Gender: "Male",
    Course: "MCA",
    Createddate: "12-FEB-21",
  },
  {
    id: "2",
    image: "images",
    Name: "hukum",
    Email: "hcgupta@cstech.in",
    phone: "954010044",
    Designation: "Hr",
    Gender: "Male",
    Course: "MCA",
    Createddate: "12-FEB-21",
  },
  {
    id: "3",
    image: "images",
    Name: "hukum",
    Email: "hcgupta@cstech.in",
    phone: "954010044",
    Designation: "Hr",
    Gender: "Male",
    Course: "MCA",
    Createddate: "12-FEB-21",
  },
  {
    id: "4",
    image: "images",
    Name: "hukum",
    Email: "hcgupta@cstech.in",
    phone: "954010044",
    Designation: "Hr",
    Gender: "Male",
    Course: "MCA",
    Createddate: "12-FEB-21",
  },
  {
    id: "5",
    image: "images",
    Name: "hukum",
    Email: "hcgupta@cstech.in",
    phone: "954010044",
    Designation: "Hr",
    Gender: "Male",
    Course: "MCA",
    Createddate: "12-FEB-21",
  },
];

